// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmnm5vUIJ9V_dcgugv0pO6_W6zkDskDD4',
    appId: '1:509723349571:web:4252f10c70cd6a43ddfaf6',
    messagingSenderId: '509723349571',
    projectId: 'cbt-quiz-app',
    authDomain: 'cbt-quiz-app.firebaseapp.com',
    storageBucket: 'cbt-quiz-app.firebasestorage.app',
    measurementId: 'G-0ZB1XQ0JVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRfTm8LEPtw_KovGzldaok7dEAJwK3Mi0',
    appId: '1:509723349571:android:6fdee4b228a704d9ddfaf6',
    messagingSenderId: '509723349571',
    projectId: 'cbt-quiz-app',
    storageBucket: 'cbt-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFYTXu2N4jsUEMUDHCRg-Udc6JVjbWDaA',
    appId: '1:509723349571:ios:805dd9d90745f3ecddfaf6',
    messagingSenderId: '509723349571',
    projectId: 'cbt-quiz-app',
    storageBucket: 'cbt-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.cbtQuizAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFYTXu2N4jsUEMUDHCRg-Udc6JVjbWDaA',
    appId: '1:509723349571:ios:805dd9d90745f3ecddfaf6',
    messagingSenderId: '509723349571',
    projectId: 'cbt-quiz-app',
    storageBucket: 'cbt-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.cbtQuizAndroid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmnm5vUIJ9V_dcgugv0pO6_W6zkDskDD4',
    appId: '1:509723349571:web:08f632fe424b37a5ddfaf6',
    messagingSenderId: '509723349571',
    projectId: 'cbt-quiz-app',
    authDomain: 'cbt-quiz-app.firebaseapp.com',
    storageBucket: 'cbt-quiz-app.firebasestorage.app',
    measurementId: 'G-GMJK3QGRQC',
  );
}
